### ISSUE TITLE
new builds are failing

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/vscode-gdsfactory#11]
How can we fix the builds for new releases?

https://github.com/gdsfactory/vscode-gdsfactory/actions

@qarlosalberto

**Comment by qarlosalberto** [comment]
I will take a look

**Comment by joamatab** [comment]
did you find the issue?

**Comment by qarlosalberto** [comment]
`chainsaw` package seems to be deprecated. Update the `package-lock.json`:

```
rm -rf package-lock.json
npm install
```
This will create a new `package-lock.json` with the dependencies updated :)

**Comment by qarlosalberto** [comment]
In the commit `0e6e391617280efe63751064eacb03bbb4218331` you updated `chainsaw` in the package-lock-json. This caused the problem:

![imagen](https://github.com/gdsfactory/vscode-gdsfactory/assets/5955143/e4d94133-5a39-41a2-bf46-b449544e0dd1)

I don't know why `chainsaw > 0.1.0` doesn't exist. But  you can follow the steps in the previous message.

**Comment by joamatab** [comment]
that worked! thank you Carlos!

https://github.com/gdsfactory/vscode-gdsfactory/releases
