### ISSUE TITLE
gdsfactory extension not working

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/vscode-gdsfactory#6]
How can we make the gdsfactory extension  showing in VScode MarketPlace again?

![image](https://user-images.githubusercontent.com/4514346/192113560-13ccc034-6e2a-4959-b82c-066878466250.png)

@qarlosalberto

**Comment by qarlosalberto** [comment]
hmmm I can see it: 

![image](https://user-images.githubusercontent.com/5955143/192113744-27e72985-ceec-4e32-a03a-391f3749a2d4.png)

**Comment by joamatab** [comment]
Maybe does not work for the latest vscode

**Comment by qarlosalberto** [comment]
I think that I have the latest version. What is your version?

**Comment by joamatab** [comment]
Im on 1.71

![image](https://user-images.githubusercontent.com/4514346/193470835-b22018e4-d52e-4472-82ac-b5d864dd0daf.png)

**Comment by qarlosalberto** [comment]
Sadly I don't know what happen... :/
