### ISSUE TITLE
Documentation needs polishing

### ISSUE THREAD

**Issue by nikosavola** [gdsfactory/vscode-gdsfactory#7]
I understand this extension is very much in-progress but currently the documentation in https://gdsfactory.github.io/gdsfactory/notebooks/_3_vscode.html#VScode does explain much about the features and use cases, and it incorrectly shows a screenshot from PyCharm. 

![image](https://user-images.githubusercontent.com/7860886/210618769-289849d2-afb6-4148-b391-4f411ec0420b.png)

**Comment by joamatab** [comment]
Hi Niko, 

yes, this is completely work in progress, at the moment it provides you only

I also fixed the docs and use VScode screenshot instead of pycharm
